name: Build FakePurchaseTweak

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar ambiente Theos
        run: |
          brew install ldid xz
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Compilar tweak
        run: |
          make package FINALPACKAGE=1

      - name: Fazer upload do .deb compilado
        uses: actions/upload-artifact@v4
        with:
          name: FakePurchaseTweak
          path: |
            packages/*.deb
            .theos/_/deb/*.deb
